Repository AY2425S1-CS2103T-T09-4/tp, pull requests merged in 2024-10, with the labels that each got.

#58 Storage: Update save functionality to support new fields: parentName, parentPhone, and parentEmail
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.Medium, type.Task, severity.Medium

#74 Logic: Add find by tags
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/findTagFriendsColleagues.png
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
Labels: priority.High, type.Enhancement

#71 Parser: Update DeleteCommand
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High, type.Story

#77 Archive Feature: Create a new class for archived contacts, interact with UniquePersonList
  src/main/java/seedu/address/model/person/ArchivedPersonList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/model/person/ArchivedPersonListTest.java
  src/test/java/seedu/address/model/person/UniqueAndArchivedPersonListTest.java
Labels: priority.Medium, type.Task, severity.Low

#91 Enable assertions in build.gradle file
  build.gradle
Labels: priority.High, type.Task

#99 Archive: Configure UI and Model for archiving students
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArchiveCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.Medium, type.Enhancement, severity.Medium

#107 UI: Add pin icon to pinned users
  docs/diagrams/BetterModelClassDiagram.puml
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/StudentListCard.fxml
Labels: priority.Medium, type.Task

#112 Archive: Update ModelClassDiagram with ArchivedPersonList
  docs/diagrams/ModelClassDiagram.puml
Labels: priority.Low, type.Task, severity.Low

#113 README.md: Add pin image attribution
  README.md
Labels: type.Task

#114 Developer Guide: Edit Model and Storage UML
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: priority.Medium, type.Task

#115 EditCommand: Added check to prevent adding parent fields to non-students
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Bug, severity.Low

#125 Diagram: update UML
  docs/diagrams/BetterModelClassDiagram.puml
Labels: type.Task

#126 Developer Guide: Update Delete sequence diagram
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: type.Task, severity.VeryLow

#136 Parser: Add ListStudents Command
  src/main/java/seedu/address/logic/commands/ListStudentsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListStudentsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Story

#152 User Guide: Update command summary
  docs/UserGuide.md
Labels: priority.High, type.Task, alpha-bug

#153 User Guide: Update archive, unarchive, listarchive
  docs/UserGuide.md
Labels: type.Task

#155 UI: Add Goat
  copyright.txt
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/GOATS_icon.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Enhancement
