Repository AY2425S1-CS2103T-T09-4/tp, pull requests merged in 2024-11, with the labels that each got.

#170 Model: Add time
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindDayCommand.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindDayCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DayContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/LessonTime.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindDayCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindDayCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
  src/test/java/seedu/address/model/person/LessonTimeTest.java
  src/test/java/seedu/address/model/person/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High, type.Enhancement, severity.High

#182 Add ListParentsCommand
  src/main/java/seedu/address/logic/commands/ListParentsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/commands/ListParentsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Story

#188 Remove Misleading Comment for Name
  src/main/java/seedu/address/model/person/Name.java
Labels: priority.Low, severity.VeryLow

#180 Fix isPinned Method Name
  src/main/java/seedu/address/logic/commands/LinkCommand.java
  src/main/java/seedu/address/logic/commands/PinCommand.java
  src/main/java/seedu/address/logic/commands/UnlinkCommand.java
  src/main/java/seedu/address/model/person/Parent.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.Low, type.Task, severity.VeryLow

#193 Model: Add time and Add FindDay
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindDayCommand.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/commands/LinkCommand.java
  src/main/java/seedu/address/logic/commands/UnlinkCommand.java
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindDayCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DayContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/LessonTime.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/tag/Education.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindDayCommandTest.java
  src/test/java/seedu/address/logic/parser/AddStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindDayCommandParserTest.java
  src/test/java/seedu/address/model/person/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High, type.Enhancement, severity.High

#200 Archive: Fixed bug, caching predicate implemented
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/UnarchiveCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddParentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
Labels: priority.High, severity.Medium, alpha-bug

#204 Fix bug with duplicate prefixes in LinkCommand
  src/main/java/seedu/address/logic/commands/LinkCommand.java
  src/main/java/seedu/address/logic/commands/UnlinkCommand.java
  src/main/java/seedu/address/logic/parser/LinkCommandParser.java
Labels: priority.Medium, type.Bug

#220 Change adds and addp command words
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddParentCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
Labels: priority.Medium, type.Task, severity.Medium

#315 UG: Fix UG command errors
  docs/UserGuide.md
Labels: UG-bug

#321 UG: Fix links in markbind
  docs/_markbind/layouts/default.md
Labels: UG-bug

#322 UG: Change Intro, Reformat UG
  docs/UserGuide.md
Labels: UG-bug
